title: HaoXuan Han's Homepage
page-top-title: Haoxuan Han 
top-section-bg-text: Computer Science
home-subtitle: Haoxuan Han&ensp;|&ensp;韩昊轩
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
